// these were scraped from the PDF manual :-)

// would like to be able to dynamically get these, some day, specifically
// for the user patches

module.exports = [
  'there is no entry for zero!',
  'hi gain stack',
  'tera echo ld',
  'natural clean',
  'power metal riff',
  'od-1 + dist',
  'layer sound',
  'fdr blues crunch',
  'od-1 + stack',
  'add transparency',
  'orng roomy lead',
  'rotary crunch',
  'ac sim straight',
  'combo ac+dc',
  'super slow gear',
  'slapback echo',
  'a-dist&overtone',
  'fat bluesy lead',
  'eg & ag mix',
  'hi:bg ld lo:1959',
  'divid organ tone',
  'combo crunch',
  'touch & go',
  'crunch lead',
  'stack crunch',
  'orng crunch',
  'single coil rock',
  'blues combo',
  'unmatched combo',
  'bee bee thrill',
  'stereo stack',
  'attacky crunch',
  'mellow lead',
  'tweed blues',
  '1959 crunch',
  'diamond echo',
  'crunch delay',
  'mid range crunch',
  'limited crunch',
  'match crunch',
  'mid boost combo',
  'king of blues',
  'country pickin\'',
  'natural over-drv',
  'basic blues',
  't-scream tweed',
  'hi gain + crunch',
  'tight crunch',
  'squeeze blues gt',
  'plexi rhythm',
  'blues buddy',
  'dirty ole tweed',
  'comp crunch lead',
  '70s small amp',
  'college rock',
  'slide for st',
  'crnch 4 rhythm',
  'tuesdays lead',
  'wild stk crunch',
  'dbl crunch 4 hum',
  'twin crunch',
  'fullertn drive',
  'uk comboforchord',
  'auto rotary 2',
  'modern vo drive',
  'power drive',
  'sync tremolo',
  'power chord!',
  'wall of dist',
  'dual mtl/crunch',
  '70s cool stack',
  'stereo stk drive',
  'ambient dirty od',
  'bosstonedrv-solo',
  'ms multi mic amb',
  'frankly sweeping',
  'fat dry mix ms',
  '70s british rock',
  'bark tone',
  '1969 xperience',
  'chained up',
  '1984 drivin\'',
  'rough\'n\' dirty',
  'creamy set',
  'stack lead',
  'great rock',
  'slide for lp',
  'fat 60s fuzz',
  'ufobject',
  'van flange',
  'wall of fuzztone',
  'octafuzz lead',
  '60s fuzz legend',
  '70s pub rock',
  'vintage & mdn',
  'pasadena plexi',
  'shred fz',
  '80s hard rock',
  '80s new wave',
  'hi gain lead',
  'bg lead',
  'harmonylead inam',
  'vintage overdrv',
  'tera echo lead',
  '70s us hard rock',
  '80s studio lead',
  'chorus lead',
  'ducking dly&vib',
  'combo lead',
  'jazz field',
  'metal stack lead',
  'brown sound 4 st',
  'overdrv lead',
  'finger lead',
  'square lead',
  'smooth lead',
  'hi gain stk lead',
  'mid boost stack',
  'match lead',
  'ballad echo lead',
  'fusion 335',
  '80s jazz fusion',
  'roads',
  'fusiony',
  'out delay',
  'royal lead',
  'mahoganyflashbak',
  '70s t .wah lead',
  'ny lead modulate',
  'mid 70s s .o .s .',
  'hi gain lead 2',
  'bgnr lead',
  'st german higain',
  'modern metal',
  'r-fier lead',
  'metal money',
  'stereo hard riff',
  'metal flanger',
  'late 80s metalrf',
  'dual st hi gain',
  'reign in thrash',
  'metal corn',
  'blade metal',
  'dragon metal',
  'hard rock flange',
  'stereo riff',
  'rectosarius',
  'jp metal unison',
  'stereo r-fier',
  'metal gt w/bass',
  'multiband comp',
  'tweed clean',
  'retro funk',
  'jazz simulator',
  'clean sustain',
  '70s funky clean',
  'bright rhythm',
  'super clean',
  'safari usa',
  'acoustic gt sim',
  'funkygt for humb',
  'black panel',
  'tera rev & comp',
  'norwegin groove',
  'funky groove',
  'deep cs stchorus',
  'funky delick',
  'jazz clean',
  'cln twinsouthern',
  'great wide open',
  'the ultra clean',
  'super modulate',
  'deep defretter',
  'rockabil50s echo',
  'e sitar simulate',
  'slicing mix',
  'rippin’',
  'multidimensional',
  'la tr riff',
  'auto rate',
  'slowgear lead',
  'wave pedal se',
  'wave synth',
  'humanizer sp',
  'reverse harmony',
  'gunya gunya',
  'seq clean',
  '5th ps & gate',
  'd’clean dirt',
  'harmo stay-4th=c',
  '[ac] ac body mid',
  '[ac]for arpeggio',
  '[ac] for strum',
  '[ac] for ac solo',
  '[ac] ac 2x2 cho',
  '[vocal] pop',
  '[vocal] ballad',
  '[vocal] rock',
  '[vocal] double',
  '[vocal]harmony c',
  '[vocal] dist', 
]
